[mainmenu]
board0 = """
<><><><><><>ff<><>
<>ff<><><>ffff<>[]
<>ff<><><><><><>mm
ff<><>......[][][]
<><>mm......[][][]
[]<>[]......<>mm[]
mm[][][]mmff<><><>
[][][][]mm<>ff<><>
[][]mm[]mm[]ff<><>
"""
portals = [{ from = 0, to = 0, x = 3, y = 3, w = 3, h = 3 }]


[levelselection]
#How much levels is in the game is determined by the biggest num here.
#E.g. having a [25] data the next level arrow would still be greyed out on level 24
board0 = """
010203
04..05
060708
"""
board1 = """
091011
12..13
141516
"""

portals = [
    { from = 0, to = 1, x = 1, y = 1, w = 1, h = 1 },
    { from = 1, to = 0, x = 1, y = 1, w = 1, h = 1 },
]


[1]
board0 = """
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][][][]........[][][][]
[][][][]........[][][][]
[][][][]........[][][][]
[][][][]........[][][][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
"""
board1 = """
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
"""
totalmine = 20 #12.2%

portals = [{ from = 0, to = 1, x = 4, y = 4, w = 4, h = 4 }]

[2]
board0 = """
[][][][][][]
[][][][][][]
[][]....[][]
[][]....[][]
[][][][][][]
[][][][][][]
"""
board1 = """
[][][][][][]
[][][][][][]
[][]....[][]
[][]....[][]
[][][][][][]
[][][][][][]
"""
board2 = """
[][][][][][]
[][][][][][]
[][]....[][]
[][]....[][]
[][][][][][]
[][][][][][]
"""
board3 = """
[][][][][][]
[][][][][][]
[][]....[][]
[][]....[][]
[][][][][][]
[][][][][][]
"""
board4 = """
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
"""
board4mine = 7

totalmine = 26 #15.8%

portals = [
    { from = 0, to = 1, x = 2, y = 2, w = 2, h = 2 },
    { from = 1, to = 2, x = 2, y = 2, w = 2, h = 2 },
    { from = 2, to = 3, x = 2, y = 2, w = 2, h = 2 },
    { from = 3, to = 4, x = 2, y = 2, w = 2, h = 2 },
]

[3]
board0 = """
[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]
[][][][][]..........[][][][][]
[][][][][]..........[][][][][]
[][][][][]..........[][][][][]
[][][][][]..........[][][][][]
[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]
"""
totalmine = 24 #15%

portals = [{ from = 0, to = 0, x = 5, y = 4, w = 5, h = 4 }]

[4]
board0 = """
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][][]............[][][]
[][][]............[][][]
[][][]............[][][]
[][][]............[][][]
[][][]............[][][]
[][][]............[][][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
"""
board1 = """
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][][]............[][][]
[][][]............[][][]
[][][]............[][][]
[][][]............[][][]
[][][]............[][][]
[][][]............[][][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
"""
totalmine = 32 #12.5%, 3-width is hard to solve

portals = [
    { from = 0, to = 1, x = 3, y = 3, w = 6, h = 6 },
    { from = 1, to = 0, x = 3, y = 3, w = 6, h = 6 },
]

[5]
board0 = """
[][][][][][][][][]
[][][][][][][][][]
[][][][][][][][][]
[][][]............
[][][]............
[][][]............
[][][]............
[][][]............
[][][]............
"""
board1 = """
[][][][][][][][][]
[][][][][][][][][]
[][][][][][][][][]
............[][][]
............[][][]
............[][][]
............[][][]
............[][][]
............[][][]
"""
board2 = """
............[][][]
............[][][]
............[][][]
............[][][]
............[][][]
............[][][]
[][][][][][][][][]
[][][][][][][][][]
[][][][][][][][][]
"""
board3 = """
[][][]............
[][][]............
[][][]............
[][][]............
[][][]............
[][][]............
[][][][][][][][][]
[][][][][][][][][]
[][][][][][][][][]
"""
totalmine = 33 #18.3%

portals = [
    { from = 0, to = 1, x = 3, y = 3, w = 6, h = 6 },
    { from = 1, to = 2, x = 0, y = 3, w = 6, h = 6 },
    { from = 2, to = 3, x = 0, y = 0, w = 6, h = 6 },
    { from = 3, to = 0, x = 3, y = 0, w = 6, h = 6 },
]

[6]
#15x15
board0 = """
[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]
[][]......................[][]
[][]......................[][]
[][]......................[][]
[][]......................[][]
[][]......................[][]
[][]......................[][]
[][]......................[][]
[][]......................[][]
[][]......................[][]
[][]......................[][]
[][]......................[][]
[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]
"""
#13x13
board1 = """
[][][][][][][][][][][][][]
[][][][][][][][][][][][][]
[][]..................[][]
[][]..................[][]
[][]..................[][]
[][]..................[][]
[][]..................[][]
[][]..................[][]
[][]..................[][]
[][]..................[][]
[][]..................[][]
[][][][][][][][][][][][][]
[][][][][][][][][][][][][]
"""
#11x11
board2 = """
[][][][][][][][][][][]
[][][][][][][][][][][]
[][]..............[][]
[][]..............[][]
[][]..............[][]
[][]..............[][]
[][]..............[][]
[][]..............[][]
[][]..............[][]
[][][][][][][][][][][]
[][][][][][][][][][][]
"""
#9x9
board3 = """
[][][][][][][][][]
[][][][][][][][][]
[][]..........[][]
[][]..........[][]
[][]..........[][]
[][]..........[][]
[][]..........[][]
[][][][][][][][][]
[][][][][][][][][]
"""
#7x7
board4 = """
[][][][][][][]
[][][][][][][]
[][]......[][]
[][]......[][]
[][]......[][]
[][][][][][][]
[][][][][][][]
"""
#5x5
board5 = """
[][][][][]
[][][][][]
[][]..[][]
[][][][][]
[][][][][]
"""

totalmine = 69 #18.0%

portals = [
    { from = 0, to = 1, x = 2, y = 2, w = 11, h = 11 },
    { from = 1, to = 2, x = 2, y = 2, w = 9, h = 9 },
    { from = 2, to = 3, x = 2, y = 2, w = 7, h = 7 },
    { from = 3, to = 4, x = 2, y = 2, w = 5, h = 5 },
    { from = 4, to = 5, x = 2, y = 2, w = 3, h = 3 },
    { from = 5, to = 0, x = 2, y = 2, w = 1, h = 1 },
]

[7]
#11x11
board0 = """
[][][][][][][][][][][]
[][][][][][][][][][][]
[][][][][][][][][][][]
[][][][][][][][][][][]
[][][][][]sf[][][][][]
......................
[][][][][]sf[][][][][]
[][][][][][][][][][][]
[][][][][][][][][][][]
[][][][][][][][][][][]
[][][][][][][][][][][]
"""
#33x3
board1 = """
[][][][][][][][][][][][][][][]......[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]......[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]......[][][][][][][][][][][][][][][]
"""
board2 = """
[][][][][]..[][][][][]
[][][][][]..[][][][][]
[][][][][]..[][][][][]
[][][][][]..[][][][][]
[][][][][]..[][][][][]
[][][][]sf..sf[][][][]
[][][][][]..[][][][][]
[][][][][]..[][][][][]
[][][][][]..[][][][][]
[][][][][]..[][][][][]
[][][][][]..[][][][][]
"""
board3 = """
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
......
......
......
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
[][][]
"""
totalmine = 60 #15%

portals = [
    { from = 0, to = 1, x = 0, y = 5, w = 11, h = 1 },
    { from = 1, to = 2, x = 15, y = 0, w = 3, h = 3 },
    { from = 2, to = 3, x = 5, y = 0, w = 1, h = 11 },
    { from = 3, to = 0, x = 0, y = 15, w = 3, h = 3 },
]

[8]
board0 = """
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
....sf[][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
"""
board1 = """
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
....sf[][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
"""
board2 = """
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][]sf....
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
"""
board3 = """
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][]sf....
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
"""
totalmine = 72 #18.9%

portals = [
    { from = 0, to = 1, x = 0, y = 3, w = 2, h = 1 },
    { from = 1, to = 2, x = 0, y = 3, w = 2, h = 1 },
    { from = 2, to = 3, x = 12, y = 3, w = 2, h = 1 },
    { from = 3, to = 0, x = 12, y = 3, w = 2, h = 1 },
]

[9]
board0 = """
[][][][]........[][][][]
[][][][]........[][][][]
[][][][]........[][][][]
[][][][]........[][][][]
........................
........................
........................
........................
[][][][]........[][][][]
[][][][]........[][][][]
[][][][]........[][][][]
[][][][]........[][][][]
"""
#40x8
board1 = """
[][][][][][][][][][][][][][][][][][][]....[][][][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]............[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]............[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]....................[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]....................[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]............[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]............[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][][][]....[][][][][][][][][][][][][][][][][][][]
"""
#6x24
board2 = """
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
............
............
............
............
............
............
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
"""

totalmine = 90 #20.3%

portals = [
    { from = 1, to = 0, x = 17, y = 1, w = 6, h = 6 },
    { from = 0, to = 2, x = 4, y = -2, w = 4, h = 16 },#yes negative is allowed
    { from = 2, to = 1, x = -12, y = 9, w = 30, h = 6 },
]

#The real game begins
[10]
board0 = """
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][]....[]....[]....[][]
[][]....[]....[]....[][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
"""
board0mine = 8
board1 = """
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
[][][][][][]
"""
board1mine = 8

portals = [
    { from = 0, to = 1, x = 2, y = 2, w = 2, h = 2, clone = true },
    { from = 0, to = 1, x = 8, y = 2, w = 2, h = 2, clone = true },
    { from = 0, to = 1, x = 5, y = 2, w = 2, h = 2 },
]

#should teach how portals work by putting the camera zoomed in
[11]
board0 = """
[][]
[][]
"""
board0mine = 1
board1 = """
[][][]
[]..[]
[][][]
"""
board2 = """
[][][][][]
[][][][][]
[][]..[][]
[][][][][]
[][][][][]
"""

board3 = """
[][][][][][][][][]
[][][][]..[][][][]
[][][][][][][][][]
[][][]......[][][]
[][][]......[][][]
[][][]......[][][]
[][][][][][][][][]
[][][][]..[][][][]
[][][][][][][][][]
"""
totalmine = 15

portals = [
    { from = 1, to = 0, x = 1, y = 1, w = 1, h = 1 },
    { from = 2, to = 1, x = 2, y = 2, w = 1, h = 1 },
    { from = 3, to = 2, x = 3, y = 3, w = 3, h = 3 },
    { from = 3, to = 2, x = 4, y = 1, w = 1, h = 1, clone = true },
    { from = 3, to = 2, x = 4, y = 7, w = 1, h = 1, clone = true },
]

[12]
board0 = """
[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]
[][][]..................[][][]
[][][]..................[][][]
[][][]..................[][][]
[][][]..................[][][]
[][][]..................[][][]
[][][]..................[][][]
[][][]..................[][][]
[][][]..................[][][]
[][][]..................[][][]
[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][]
"""
board0mine = 10
board1 = """
[][][][][][][]
[][][][][][][]
[][]......[][]
[][]......[][]
[][]......[][]
[][][][][][][]
[][][][][][][]
"""
board2 = """
[][][][][][][]
[][][][][][][]
[][]......[][]
[][]......[][]
[][]......[][]
[][][][][][][]
[][][][][][][]
"""
board3 = """
[][][][][][][]
[][][][][][][]
[][]......[][]
[][]......[][]
[][]......[][]
[][][][][][][]
[][][][][][][]
"""
totalmine = 40

portals = [
    { from = 0, to = 1, x = 3, y = 3, w = 9, h = 9 },
    { from = 1, to = 2, x = 2, y = 2, w = 3, h = 3 },
    { from = 2, to = 3, x = 2, y = 2, w = 3, h = 3 },
    { from = 3, to = 1, x = 2, y = 2, w = 3, h = 3, clone = true },
]

[13]
board0 = """
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][]........[][][][][]
[]....[][]........[][]....[]
[]....[][]........[][]....[]
[][][][][]........[][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
[][][][][][][][][][][][][][]
"""
board0mine = 8
board1 = """
[][][][][][][][]
[][][][][][][][]
[][]........[][]
[][]........[][]
[][]........[][]
[][]........[][]
[][][][][][][][]
[][][][][][][][]
"""
totalmine = 30

portals = [
    { from = 0, to = 1, x = 5, y = 5, w = 4, h = 4 },
    { from = 0, to = 1, x = 1, y = 6, w = 2, h = 2, clone = true },
    { from = 0, to = 1, x = 11, y = 6, w = 2, h = 2, clone = true },
    { from = 1, to = 0, x = 2, y = 2, w = 4, h = 4 },
]

[14]
board0 = """
[][][][][][][][]
[][][][][][][][]
[][]........[][]
[][]........[][]
[][]........[][]
[][]........[][]
[][][][][][][][]
[][][][][][][][]
"""
board0mine = 8
board1 = """
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
"""
board2 = """
[][][][][][][][]
[][][][][][][][]
[][]........[][]
[][]........[][]
[][]........[][]
[][]........[][]
[][][][][][][][]
[][][][][][][][]
"""
board2mine = 8
board3 = """
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
"""
board4 = """
[][][][][][][][]
[][][][][][][][]
[][]........[][]
[][]........[][]
[][]........[][]
[][]........[][]
[][][][][][][][]
[][][][][][][][]
"""
board4mine = 8
board5 = """
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
"""
board6 = """
[][][][][][][][]
[][][][][][][][]
[][]........[][]
[][]........[][]
[][]........[][]
[][]........[][]
[][][][][][][][]
[][][][][][][][]
"""
board6mine = 8
board7 = """
[][][][][][][][][][][][]
[][][][][][][][][][][][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][]................[][]
[][][][][][][][][][][][]
[][][][][][][][][][][][]
"""
totalmine = 60 #only 11.7% because it's just that hard

portals = [
    { from = 1, to = 0, x = 2, y = 2, w = 8, h = 8 },
    { from = 3, to = 2, x = 2, y = 2, w = 8, h = 8 },
    { from = 5, to = 4, x = 2, y = 2, w = 8, h = 8 },
    { from = 7, to = 6, x = 2, y = 2, w = 8, h = 8 },

    { from = 0, to = 2, x = 2, y = 2, w = 4, h = 4, clone = true },
    { from = 2, to = 4, x = 2, y = 2, w = 4, h = 4, clone = true },
    { from = 4, to = 6, x = 2, y = 2, w = 4, h = 4, clone = true },
    { from = 6, to = 0, x = 2, y = 2, w = 4, h = 4, clone = true },
]

[15]
board0 = """
[][][][][][][][][]
[]..[][]..[][]..[]
[][][][][][][][][]
[][][]......[][][]
[]..[]......[]..[]
[][][]......[][][]
[][][][][][][][][]
[]..[][]..[][]..[]
[][][][][][][][][]
"""
board1 = """
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][]....[][][][][][][]
[][][][][][][]....[][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
"""
totalmine = 40
portals = [
    { from = 0, to = 1, x = 1, y = 1, w = 1, h = 1, clone = true },
    { from = 0, to = 1, x = 4, y = 1, w = 1, h = 1, clone = true },
    { from = 0, to = 1, x = 7, y = 1, w = 1, h = 1, clone = true },
    { from = 0, to = 1, x = 1, y = 4, w = 1, h = 1, clone = true },
    { from = 0, to = 1, x = 3, y = 3, w = 3, h = 3 },
    { from = 0, to = 1, x = 7, y = 4, w = 1, h = 1, clone = true },
    { from = 0, to = 1, x = 1, y = 7, w = 1, h = 1, clone = true },
    { from = 0, to = 1, x = 4, y = 7, w = 1, h = 1, clone = true },
    { from = 0, to = 1, x = 7, y = 7, w = 1, h = 1, clone = true },
    { from = 1, to = 0, x = 7, y = 7, w = 2, h = 2 },
]
